# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'momag_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import h5py
from PyQt5 import QtWidgets, QtCore
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtGui import QPixmap
from PyQt5.QtGui import QImage
import cv2

from momag_ import run_momag

class GUIWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frames = QtWidgets.QLabel(self.centralwidget)
        self.frames.setGeometry(QtCore.QRect(110, 40, 581, 401))
        self.frames.setText("")
        self.frames.setObjectName("frames")
        self.frame_slider = QtWidgets.QSlider(self.centralwidget)
        self.frame_slider.setGeometry(QtCore.QRect(80, 470, 671, 22))
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 560, 281, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_frame_zero = QtWidgets.QLabel(self.centralwidget)
        self.label_frame_zero.setGeometry(QtCore.QRect(90, 506, 51, 20))
        self.label_frame_zero.setText("")
        self.label_frame_zero.setObjectName("label_frame_zero")
        self.label_frame_n = QtWidgets.QLabel(self.centralwidget)
        self.label_frame_n.setGeometry(QtCore.QRect(180, 505, 121, 21))
        self.label_frame_n.setText("")
        self.label_frame_n.setObjectName("label_frame_n")
        self.frame_number = QtWidgets.QLabel(self.centralwidget)
        self.frame_number.setGeometry(QtCore.QRect(100, 20, 141, 20))
        self.frame_number.setText("")
        self.frame_number.setObjectName("frame_number")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 500, 21, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 500, 21, 31))
        self.label_2.setObjectName("label_2")
        self.run_motion_magnification = QtWidgets.QPushButton(self.centralwidget)
        self.run_motion_magnification.setGeometry(QtCore.QRect(600, 560, 161, 51))
        self.run_motion_magnification.setObjectName("run_motion_magnification")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 590, 31, 40))
        self.label_3.setObjectName("label_3")
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(490, 600, 61, 20))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 620, 91, 40))
        self.label_4.setObjectName("label_4")
        self.lineEdit_frame_rate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frame_rate.setGeometry(QtCore.QRect(540, 630, 61, 20))
        self.lineEdit_frame_rate.setObjectName("lineEdit_frame_rate")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 500, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_total_frames = QtWidgets.QLabel(self.centralwidget)
        self.label_total_frames.setGeometry(QtCore.QRect(630, 500, 121, 21))
        self.label_total_frames.setText("")
        self.label_total_frames.setObjectName("label_total_frames")
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setGeometry(QtCore.QRect(510, 660, 161, 20))
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 650, 51, 40))
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(400, 550, 20, 131))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 560, 111, 20))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_HDF_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_HDF_File.setObjectName("actionLoad_HDF_File")
        self.menuFile.addAction(self.actionLoad_HDF_File)
        self.menubar.addAction(self.menuFile.menuAction())
        self.start_frame = None

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Load HDF5"))
        self.pushButton.setText(_translate("MainWindow", "Select Frames"))
        self.label.setText(_translate("MainWindow", "F0:"))
        self.label_2.setText(_translate("MainWindow", "FN:"))
        self.run_motion_magnification.setText(_translate("MainWindow", "Run Motion Magnification"))
        self.label_3.setText(_translate("MainWindow", "alpha:"))
        self.label_4.setText(_translate("MainWindow", "video frame rate:"))
        self.label_5.setText(_translate("MainWindow", "total frames selected:"))
        self.label_6.setText(_translate("MainWindow", "file name:"))
        self.label_7.setText(_translate("MainWindow", "Configuration:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_HDF_File.setText(_translate("MainWindow", "Load HDF File"))

    def loadHDFFile(self):
        self.fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Open HDF File", "", "HDF Files (*.hdf *.h5)")
        if self.fileName:
            self.hdfFile = h5py.File(self.fileName, 'r')
            self.framesGenerator = self.frameGenerator()

            frameCount = self.hdfFile['Frames'].shape[0]
            self.frame_slider.setMaximum(frameCount - 1)
            self.updateFrame(0)

    def frameGenerator(self):
        for frame in self.hdfFile['Frames']:
            yield frame

    def updateFrame(self, frameIndex):
        if hasattr(self, 'framesGenerator'):
            self.frame_number.setText(f'{frameIndex}')
            self.hdfFile['Frames'].id.refresh()
            frame = self.hdfFile['Frames'][frameIndex]

            aligned = cv2.resize(frame, (frame.shape[1] // 4 * 4, frame.shape[0] // 4 * 4), fx=0, fy=0,
                                 interpolation=cv2.INTER_NEAREST)
            rgb = cv2.cvtColor(aligned, cv2.COLOR_BGR2RGB)

            new_width = 581
            old_width, old_height = rgb.shape[1], rgb.shape[0]
            ratio = new_width / old_width

            new_height = int(old_height * ratio)

            resized_image = cv2.resize(rgb, (new_width, new_height))

            qimage = QImage(resized_image.data, resized_image.shape[1], resized_image.shape[0],
                            QImage.Format_RGB888)
            pixmap = QPixmap.fromImage(qimage)
            self.frames.setPixmap(pixmap)

    def selectFrame(self):
        currentFrame = self.frame_slider.value()
        if not hasattr(self, 'labelFrameZeroSet'):
            self.label_frame_zero.setText(str(currentFrame))
            self.start_frame = int(currentFrame)
            self.labelFrameZeroSet = True
            with open(f'frames.txt', 'w') as f:
                f.write(f"frame_0={int(currentFrame)}\n")
                f.close()
        else:
            self.label_frame_n.setText(str(currentFrame))

            with open(f'frames.txt', 'a') as f:
                f.write(f"frame_n={int(currentFrame)}\n")

            self.label_total_frames.setText(f'{int(currentFrame-self.start_frame)}')

    def momag(self):
        frame_0_value = None
        frame_n_value = None

        with open('frames.txt', 'r') as file:
            for line in file:
                if 'frame_0=' in line:
                    frame_0_value = int(line.split('=')[1].strip())
                elif 'frame_n=' in line:
                    frame_n_value = int(line.split('=')[1].strip())

        run_momag(path_to_hdf_file=self.fileName,
                  frame_zero=frame_0_value,
                  frame_n=frame_n_value,
                  alpha=int(self.lineEdit_alpha.text()),
                  frame_rate=int(self.lineEdit_frame_rate.text()),
                  file_name=self.lineEdit_file_name.text())
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = GUIWindow()
        self.ui.setupUi(self)

        # Connect signals to slots
        self.ui.actionLoad_HDF_File.triggered.connect(self.ui.loadHDFFile)
        self.ui.frame_slider.valueChanged.connect(self.ui.updateFrame)
        self.ui.pushButton.clicked.connect(self.ui.selectFrame)

        self.ui.run_motion_magnification.clicked.connect(self.ui.momag)


def main():
    app = QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
